# Generated by Django 4.1 on 2023-03-14 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bikes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand', models.CharField(help_text='The name of the brand.', max_length=50)),
                ('bike_type', models.CharField(help_text='The type of the bike.', max_length=20)),
                ('bike_model', models.CharField(help_text='The model of the bike.', max_length=20)),
                ('price', models.IntegerField(help_text='The price of the bike.')),
                ('weight', models.DecimalField(decimal_places=1, help_text='The weight of bike.', max_digits=3)),
                ('color', models.CharField(help_text='The color of the frame.', max_length=20)),
            ],
        ),
    ]
