# Generated by Django 4.1 on 2023-03-15 15:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bikes',
            name='brand',
            field=models.CharField(help_text='  xx  ', max_length=50),
        ),
        migrations.AlterField(
            model_name='bikes',
            name='weight',
            field=models.DecimalField(decimal_places=2, help_text='The weight of bike.', max_digits=4),
        ),
        migrations.CreateModel(
            name='Specification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('frame', models.CharField(help_text='Desctription of frame.', max_length=120)),
                ('fork', models.CharField(help_text='Material and type of lork.', max_length=120)),
                ('handlebar', models.CharField(help_text='Details of handlebar', max_length=120)),
                ('handle_tape', models.CharField(help_text='Details of handle tape.', max_length=120)),
                ('stem', models.CharField(help_text='Details of stem.', max_length=120)),
                ('seatpost', models.CharField(help_text='Details of seatpost.', max_length=120)),
                ('saddle', models.CharField(help_text='Details of saddle.', max_length=120)),
                ('shift', models.CharField(help_text='Details of shifter.', max_length=120)),
                ('front_derailleur', models.CharField(help_text='Details of front derailleur.', max_length=120)),
                ('rear_derailleur', models.CharField(help_text='Details of rear derailleur.', max_length=120)),
                ('brake', models.CharField(help_text='Details of brakes.', max_length=120)),
                ('brake_lever', models.CharField(help_text='Details of break lever.', max_length=120)),
                ('cassette', models.CharField(help_text='Details of cassette.', max_length=120)),
                ('chain', models.CharField(help_text='Details of chain.', max_length=120)),
                ('crankset', models.CharField(help_text='Details of crankset.', max_length=120)),
                ('bottom_bracket', models.CharField(help_text='Details of bottom bracket.', max_length=120)),
                ('wheel', models.CharField(help_text='Details of wheel', max_length=120)),
                ('thru_axle', models.CharField(help_text='Details of thru axle', max_length=120)),
                ('tyre', models.CharField(help_text='Details of tyre', max_length=120)),
                ('bikes', models.ForeignKey(help_text='The Book that this specification is for.', on_delete=django.db.models.deletion.CASCADE, to='products.bikes')),
            ],
        ),
    ]
